### ISSUE TITLE
v2.0.1.0 assembly is not strongly named

### ISSUE THREAD

**Issue by Arbalets** [jagregory/fluent-nhibernate#295]
The latest version (v2.0.1.0) available via NuGet is not strongly named.
Please sign the assembly.

**Comment by chester89** [comment]
That was the idea - not to give it a strong name.

**Comment by alberto-chiesa** [comment]
First of all, THANKS! For everything.
Then, I can understand it was done intentionally, but why?

I have to sign the assemblies of my own projects. Because of that, I need that every assembly I reference has to be strongly named.

How am I supposed to solve this scenario?
Currently, I cannot use the Nuget provided Fluent Nhibernate because of this.

I would reverse the question: given the nature of Fluent as a library that should be referenced in many different projects, why NOT strongly naming it?

Thanks again for your precious time: this library is a jewel (and I would like to keep using it without resorting to self-signing!).

**Comment by alberto-chiesa** [comment]
AFAICT, the only problem is in case Fluent references some unsigned assembly.
Currently, NHibernate ships with strongly named assemblies thorugh Nuget (I'm looking at version 4.0.0.4000, the latest available for .NET 4.5).
So, there shouldn't be any problem, if using the Nuget-provided NHibernate package.
If doing custom, not stronlgy named, NH builds, one would have to resort to custom builds of Fluent too.

**Comment by bcsanches** [comment]
Having trouble here too due to this. Why it was not strong named?

**Comment by jagregory** [comment]
Strong naming has been a pain in the side of open-source developers for a long time in .Net. There's been a gradual shift over the years to move away from it unless absolutely necessary. Jeremy Miller has a [nice writeup about his experiences](http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/) with strong named OSS libs and Fubu MVC.

**Caveat**: I was not involved in this decision, I'm just providing general context.

**Comment by gianos** [comment]
Thanks for the insight and the article!
I temporarily forked the repository in order to package my own signed version of Fluent.
In fact, I just needed to re-enable the signing with the key that is already in the repo, and the build went on smoothly (on the Visual Studio side, I couldn't get the Rake scripts to work, probably because I don't have a clue about the tool).

I would just say that, in the OSS context, strong naming is pretty useless, but currently is the only way I know in order to check that my commercial projects assemblies didn't get tampered with.
I'm just mentioning because I'm wondering about the available options.

Thanks again for your time! Fluent is THE way to go NHibernate.

**Comment by bcsanches** [comment]
@jagregory thanks for providing the insights about it.
