### ISSUE TITLE
In ClassMap, DiscriminateSubClassesOnColumn with Map throws an odd error

### ISSUE THREAD

**Issue by bradlis7** [jagregory/fluent-nhibernate#329]
In my ClassMap, I had this:

    Map(x => x.Column);
    DiscriminateSubClassesOnColumn("Column");

The error was something like this when trying to insert certain items:

    Invalid index 4 for this SqlParameterCollection with Count=4

There really wasn't much to go on for debugging. The fix was to add `.ReadOnly()` to the `DiscriminateSubClassesOnColumn("Column")` call.

I'd be ok with adding something to the documentation, but this was not an easy bug to troubleshoot.

**Comment by Trinition** [comment]
You have four parameters for the eventual SQL query (indexes 0 through 3),
but the query itself refers to five (indexes 0 -  4). So when it tries to
get the last parameter (index 4), there isn't one. Hence, the message.

Why the mismatch? Because you've confused NHibernate (and one part of NH
thinks differently than the other). The confusion comes from your column
being both mapped *and* the discriminator. The query building part of
NHibernate sees those two things and decides to put the column named
"Column" into the query twice. But the parameter filling part doesn't think
it needs the value twice. So you end up with one fewer parameter values
than the SQL query actually needs.

I've run into this myself? Do you really need the column as a property
*and* discriminatory? The discrimination enables polymorphism, so you might
find an OO way out of your need for that property. I know I did in some of
my cases.

For one, though, I didn't. I think I used a column value derived from a
function then (and the function was just getting that other column) as a
work around.

**Comment by bradlis7** [comment]
Yeah, it makes sense, but I would think NHibernate could work around this, and know not to map it. I don't really know or care to know the inner workings, so maybe I'm wrong.

I think my coworker had added `.ReadOnly()` originally, but when trying to initiate the base class (when creating), the value wasn't being saved the in database (rightly so, it's readonly). I then started using the derived classes, and it seems like it was working (either by setting the class, or because of the discriminator). Without the map, the Column was not assigned. Maybe we should have been evaluating `entity.GetType()` instead of `entity.Column`.

For now `.ReadOnly()` fixed it for us. I'd suggest that the documentation should show that the Column will not be mapped, and give an example of how to determine the correct type.

**Comment by Trinition** [comment]
For the sake of clarity, I think we're saying not just "Column won't be mapped", but that "the query will fail" (due to the parameter count / index mismatch).

As for the documentation, I'm not sure of the intent of the FNH docs.  Is it do document how FNH exposes NHibernate mapping, or does it also document NHibernate oddities.  Because the problem of the parameter index/count mismatch isn't a Fluent NHibernate problem, but an NHibernate problem (and I'd bet money it's a problem originating from Hibernate).

As for the alternative solutions, the `.ReadOnly()` is an interesting one.

The other solution I used was `.Formula(...)`.  So it would look something like:
```csharp
Map(x => x.Column); // column name will be "Column", by convention
DiscriminateSubClassesOnColumn("").Formula("Column"); // The actual discriminator value will be determined by evaluating in the SQL query the value of the expression 'Column'
```

The *purist* solution is to do away with having to know your discriminator.  As you suggested, you could use `entity.GetType()`.  But even an OO-purist would balm at that (and we are using **O**RM).  So you'd have to examine the places where you were consuming the discriminator/type and instead call a polymorphic method on `entity`.

**Comment by bradlis7** [comment]
Yeah, this is a problem with Hibernate.

I was assuming you were involved with this project the whole time, but I don't see you listed anywhere. Should I mark it closed, or wait for an admin?

**Comment by Trinition** [comment]
Don't rely on me!  I'm just another FNH user.  I saw your bug and it was something I had experience with, so I wanted to give back to the community by sharing what knowledge I had.

**Comment by chester89** [comment]
So @Trinition @bradlis7 is it Hibernate problem? can I close the issue?

**Comment by bradlis7** [comment]
I'd say it is. Thanks

**Comment by Trinition** [comment]
I concur.
